# Generated by Django 6.0.5 on 2026-06-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='feedback',
            field=models.TextField(default='python'),
            preserve_default=False,
        ),
    ]
