# Generated by Django 6.0.5 on 2026-06-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_review_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='feedback',
        ),
    ]
