# Generated by Django 6.0.5 on 2026-06-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_review_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default='Not Found', max_length=100),
            preserve_default=False,
        ),
    ]
